Repository TencentBlueKing/bkui-vue3, pull requests merged in 2025-09, with the labels that each got.

#2461 feature(navigation): 导航组件希望支持新的交互规范 #2413
  packages/menu/src/menu.less
  packages/navigation/src/navigation.less
  packages/styles/src/themes/themes.less
Labels: for test

#2463 bugfix(resize-layout): aside-bottom的时候把手位置异常 #2462
  packages/resize-layout/src/resize-layout.less
  site/views/resize-layout/advance-demo.vue
Labels: bug, backlog, for test, doing, todo

#2457 feature(search-select): 支持 copy 事件并回调可修改用户复制内容 #2456
  packages/search-select/src/input.tsx
  packages/search-select/src/search-select.tsx
  packages/search-select/src/utils.ts
  site/views/search-select/index.tsx
Labels: for test, doing

#2454 fix: searchSelect getMenuList是异步的时候复制就不会触发这个get-menu-list方法 #2452
  package.json
  packages/search-select/src/input.tsx
Labels: bug, doing
